project_id = "lckxvimdqnfjzkbrusgu"

[functions.generate-blog-post]
verify_jwt = true

[functions.create-payment]
verify_jwt = true

[functions.create-booking-payment]
verify_jwt = true

[functions.verify-booking-payment]
verify_jwt = true

[functions.send-booking-confirmation]
verify_jwt = true

[functions.translate-service]
verify_jwt = true

[functions.ai-format-input]
verify_jwt = true
