import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    // Include only relevant files for better performance
    "./src/**/*.{js,ts,jsx,tsx}",
    "./index.html",
    // Exclude test and mock files
    "!./src/**/*.{test,spec}.{js,ts,jsx,tsx}",
    "!./src/mocks/**/*",
    "!./src/test/**/*",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        brand: {
          DEFAULT: "hsl(var(--brand))",
          foreground: "hsl(var(--brand-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Enhanced Color System - Cocoa
        cocoa: {
          50: "hsl(var(--cocoa-50))",
          100: "hsl(var(--cocoa-100))",
          200: "hsl(var(--cocoa-200))",
          300: "hsl(var(--cocoa-300))",
          400: "hsl(var(--cocoa-400))",
          500: "hsl(var(--cocoa))",
          600: "hsl(var(--cocoa-600))",
          700: "hsl(var(--cocoa-700))",
          800: "hsl(var(--cocoa-800))",
          900: "hsl(var(--cocoa-900))",
          DEFAULT: "hsl(var(--cocoa))",
          foreground: "hsl(var(--cocoa-foreground))",
        },
        // Charcoal System
        charcoal: {
          50: "hsl(var(--charcoal-50))",
          100: "hsl(var(--charcoal-100))",
          200: "hsl(var(--charcoal-200))",
          300: "hsl(var(--charcoal-300))",
          400: "hsl(var(--charcoal-400))",
          500: "hsl(var(--charcoal))",
          600: "hsl(var(--charcoal-600))",
          700: "hsl(var(--charcoal-700))",
          800: "hsl(var(--charcoal-800))",
          900: "hsl(var(--charcoal-900))",
          DEFAULT: "hsl(var(--charcoal))",
          foreground: "hsl(var(--charcoal-foreground))",
        },
        // Pearl System
        pearl: {
          50: "hsl(var(--pearl-50))",
          100: "hsl(var(--pearl-100))",
          200: "hsl(var(--pearl-200))",
          300: "hsl(var(--pearl-300))",
          400: "hsl(var(--pearl-400))",
          500: "hsl(var(--pearl))",
          600: "hsl(var(--pearl-600))",
          700: "hsl(var(--pearl-700))",
          800: "hsl(var(--pearl-800))",
          900: "hsl(var(--pearl-900))",
          DEFAULT: "hsl(var(--pearl))",
          foreground: "hsl(var(--pearl-foreground))",
        },
        // Champagne/Rose Gold System
        champagne: {
          50: "hsl(var(--champagne-50))",
          100: "hsl(var(--champagne-100))",
          200: "hsl(var(--champagne-200))",
          300: "hsl(var(--champagne-300))",
          400: "hsl(var(--champagne-400))",
          500: "hsl(var(--champagne))",
          600: "hsl(var(--champagne-600))",
          700: "hsl(var(--champagne-700))",
          800: "hsl(var(--champagne-800))",
          900: "hsl(var(--champagne-900))",
          DEFAULT: "hsl(var(--champagne))",
          foreground: "hsl(var(--champagne-foreground))",
        },
        // Bronze System
        bronze: {
          50: "hsl(var(--bronze-50))",
          100: "hsl(var(--bronze-100))",
          200: "hsl(var(--bronze-200))",
          300: "hsl(var(--bronze-300))",
          400: "hsl(var(--bronze-400))",
          500: "hsl(var(--bronze))",
          600: "hsl(var(--bronze-600))",
          700: "hsl(var(--bronze-700))",
          800: "hsl(var(--bronze-800))",
          900: "hsl(var(--bronze-900))",
          DEFAULT: "hsl(var(--bronze))",
          foreground: "hsl(var(--bronze-foreground))",
        },
        // Rose Gold System
        "rose-gold": {
          50: "hsl(var(--rose-gold-50))",
          100: "hsl(var(--rose-gold-100))",
          200: "hsl(var(--rose-gold-200))",
          300: "hsl(var(--rose-gold-300))",
          400: "hsl(var(--rose-gold-400))",
          500: "hsl(var(--lip-rose))",
          600: "hsl(var(--rose-gold-600))",
          700: "hsl(var(--rose-gold-700))",
          800: "hsl(var(--rose-gold-800))",
          900: "hsl(var(--rose-gold-900))",
          DEFAULT: "hsl(var(--lip-rose))",
          foreground: "hsl(var(--lip-rose-foreground))",
        },
        // Legacy Lip Rose
        "lip-rose": {
          DEFAULT: "hsl(var(--lip-rose))",
          foreground: "hsl(var(--lip-rose-foreground))",
        },
        // Soft Gold System
        "soft-gold": {
          50: "hsl(var(--soft-gold-50))",
          100: "hsl(var(--soft-gold-100))",
          200: "hsl(var(--soft-gold-200))",
          300: "hsl(var(--soft-gold-300))",
          400: "hsl(var(--soft-gold-400))",
          500: "hsl(var(--soft-gold))",
          600: "hsl(var(--soft-gold-600))",
          700: "hsl(var(--soft-gold-700))",
          800: "hsl(var(--soft-gold-800))",
          900: "hsl(var(--soft-gold-900))",
          DEFAULT: "hsl(var(--soft-gold))",
          foreground: "hsl(var(--soft-gold-foreground))",
        },
        // Graphite System
        graphite: {
          50: "hsl(var(--graphite-50))",
          100: "hsl(var(--graphite-100))",
          200: "hsl(var(--graphite-200))",
          300: "hsl(var(--graphite-300))",
          400: "hsl(var(--graphite-400))",
          500: "hsl(var(--graphite))",
          600: "hsl(var(--graphite-600))",
          700: "hsl(var(--graphite-700))",
          800: "hsl(var(--graphite-800))",
          900: "hsl(var(--graphite-900))",
          DEFAULT: "hsl(var(--graphite))",
          foreground: "hsl(var(--graphite-foreground))",
        },
        // Sage System
        sage: {
          50: "hsl(var(--sage-50))",
          100: "hsl(var(--sage-100))",
          200: "hsl(var(--sage-200))",
          300: "hsl(var(--sage-300))",
          400: "hsl(var(--sage-400))",
          500: "hsl(var(--sage))",
          600: "hsl(var(--sage-600))",
          700: "hsl(var(--sage-700))",
          800: "hsl(var(--sage-800))",
          900: "hsl(var(--sage-900))",
          DEFAULT: "hsl(var(--sage))",
          foreground: "hsl(var(--sage-foreground))",
        },
        // Semantic Colors
        success: {
          50: "hsl(var(--success-50))",
          100: "hsl(var(--success-100))",
          200: "hsl(var(--success-200))",
          300: "hsl(var(--success-300))",
          400: "hsl(var(--success-400))",
          500: "hsl(var(--success))",
          600: "hsl(var(--success-600))",
          700: "hsl(var(--success-700))",
          800: "hsl(var(--success-800))",
          900: "hsl(var(--success-900))",
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        warning: {
          50: "hsl(var(--warning-50))",
          100: "hsl(var(--warning-100))",
          200: "hsl(var(--warning-200))",
          300: "hsl(var(--warning-300))",
          400: "hsl(var(--warning-400))",
          500: "hsl(var(--warning))",
          600: "hsl(var(--warning-600))",
          700: "hsl(var(--warning-700))",
          800: "hsl(var(--warning-800))",
          900: "hsl(var(--warning-900))",
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
        error: {
          50: "hsl(var(--error-50))",
          100: "hsl(var(--error-100))",
          200: "hsl(var(--error-200))",
          300: "hsl(var(--error-300))",
          400: "hsl(var(--error-400))",
          500: "hsl(var(--error))",
          600: "hsl(var(--error-600))",
          700: "hsl(var(--error-700))",
          800: "hsl(var(--error-800))",
          900: "hsl(var(--error-900))",
          DEFAULT: "hsl(var(--error))",
          foreground: "hsl(var(--error-foreground))",
        },
        info: {
          50: "hsl(var(--info-50))",
          100: "hsl(var(--info-100))",
          200: "hsl(var(--info-200))",
          300: "hsl(var(--info-300))",
          400: "hsl(var(--info-400))",
          500: "hsl(var(--info))",
          600: "hsl(var(--info-600))",
          700: "hsl(var(--info-700))",
          800: "hsl(var(--info-800))",
          900: "hsl(var(--info-900))",
          DEFAULT: "hsl(var(--info))",
          foreground: "hsl(var(--info-foreground))",
        },
      },
      backgroundImage: {
        'gradient-brand': 'var(--gradient-brand)',
        'gradient-luxury': 'var(--gradient-luxury)',
        'gradient-luxury-reverse': 'var(--gradient-luxury-reverse)',
        'gradient-luxury-subtle': 'var(--gradient-luxury-subtle)',
        'gradient-rose': 'var(--gradient-rose)',
        'gradient-rose-subtle': 'var(--gradient-rose-subtle)',
        'gradient-champagne': 'var(--gradient-champagne)',
        'gradient-champagne-vertical': 'var(--gradient-champagne-vertical)',
        'gradient-bronze': 'var(--gradient-bronze)',
        'gradient-subtle': 'var(--gradient-subtle)',
        'gradient-hero': 'var(--gradient-hero)',
        'gradient-overlay': 'var(--gradient-overlay)',
        'gradient-glass': 'var(--gradient-glass)',
      },
      boxShadow: {
        'inner-subtle': 'var(--shadow-inner-subtle)',
        'inner': 'var(--shadow-inner)',
        'inner-strong': 'var(--shadow-inner-strong)',
        'soft': 'var(--shadow-soft)',
        'medium': 'var(--shadow-medium)',
        'strong': 'var(--shadow-strong)',
        'luxury': 'var(--shadow-luxury)',
        'luxury-strong': 'var(--shadow-luxury-strong)',
        'glass-xs': 'var(--glass-shadow-xs)',
        'glass-sm': 'var(--glass-shadow-sm)',
        'glass-md': 'var(--glass-shadow-md)',
        'glass-lg': 'var(--glass-shadow-lg)',
        'glass-xl': 'var(--glass-shadow-xl)',
      },
      fontFamily: {
        'display': ['var(--font-display)', 'system-ui', 'sans-serif'],
        'body': ['var(--font-body)', 'system-ui', 'sans-serif'],
        'serif': ['var(--font-serif)', 'Georgia', 'serif'],
        'mono': ['var(--font-mono)', 'monospace'],
      },
      fontSize: {
        'xs': ['var(--text-xs)', { lineHeight: 'var(--leading-tight)', letterSpacing: 'var(--tracking-normal)' }],
        'sm': ['var(--text-sm)', { lineHeight: 'var(--leading-normal)', letterSpacing: 'var(--tracking-normal)' }],
        'base': ['var(--text-base)', { lineHeight: 'var(--leading-normal)', letterSpacing: 'var(--tracking-normal)' }],
        'lg': ['var(--text-lg)', { lineHeight: 'var(--leading-relaxed)', letterSpacing: 'var(--tracking-normal)' }],
        'xl': ['var(--text-xl)', { lineHeight: 'var(--leading-relaxed)', letterSpacing: 'var(--tracking-tight)' }],
        '2xl': ['var(--text-2xl)', { lineHeight: 'var(--leading-tight)', letterSpacing: 'var(--tracking-tight)' }],
        '3xl': ['var(--text-3xl)', { lineHeight: 'var(--leading-tight)', letterSpacing: 'var(--tracking-tighter)' }],
        '4xl': ['var(--text-4xl)', { lineHeight: 'var(--leading-tight)', letterSpacing: 'var(--tracking-tighter)' }],
        '5xl': ['var(--text-5xl)', { lineHeight: 'var(--leading-none)', letterSpacing: 'var(--tracking-tighter)' }],
      },
      fontWeight: {
        'thin': 'var(--font-thin)',
        'light': 'var(--font-light)',
        'normal': 'var(--font-normal)',
        'medium': 'var(--font-medium)',
        'semibold': 'var(--font-semibold)',
        'bold': 'var(--font-bold)',
        'extrabold': 'var(--font-extrabold)',
        'black': 'var(--font-black)',
      },
      letterSpacing: {
        'tighter': 'var(--tracking-tighter)',
        'tight': 'var(--tracking-tight)',
        'normal': 'var(--tracking-normal)',
        'wide': 'var(--tracking-wide)',
        'wider': 'var(--tracking-wider)',
        'widest': 'var(--tracking-widest)',
      },
      lineHeight: {
        'none': 'var(--leading-none)',
        'tight': 'var(--leading-tight)',
        'snug': 'var(--leading-snug)',
        'normal': 'var(--leading-normal)',
        'relaxed': 'var(--leading-relaxed)',
        'loose': 'var(--leading-loose)',
      },
      spacing: {
        '0': 'var(--space-0)',
        'px': 'var(--space-px)',
        '0.5': 'var(--space-0_5)',
        '1': 'var(--space-1)',
        '1.5': 'var(--space-1_5)',
        '2': 'var(--space-2)',
        '2.5': 'var(--space-2_5)',
        '3': 'var(--space-3)',
        '3.5': 'var(--space-3_5)',
        '4': 'var(--space-4)',
        '5': 'var(--space-5)',
        '6': 'var(--space-6)',
        '7': 'var(--space-7)',
        '8': 'var(--space-8)',
        '9': 'var(--space-9)',
        '10': 'var(--space-10)',
        '11': 'var(--space-11)',
        '12': 'var(--space-12)',
        '14': 'var(--space-14)',
        '16': 'var(--space-16)',
        '20': 'var(--space-20)',
        '24': 'var(--space-24)',
        '28': 'var(--space-28)',
        '32': 'var(--space-32)',
        '36': 'var(--space-36)',
        '40': 'var(--space-40)',
        '44': 'var(--space-44)',
        '48': 'var(--space-48)',
        '52': 'var(--space-52)',
        '56': 'var(--space-56)',
        '60': 'var(--space-60)',
        '64': 'var(--space-64)',
        '72': 'var(--space-72)',
        '80': 'var(--space-80)',
        '96': 'var(--space-96)',
      },
      borderRadius: {
        'none': 'var(--radius-none)',
        'xs': 'var(--radius-xs)',
        'sm': 'var(--radius-sm)',
        'md': 'var(--radius-md)',
        'lg': 'var(--radius-lg)',
        'xl': 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        '3xl': 'var(--radius-3xl)',
        'full': 'var(--radius-full)',
      },
      transitionProperty: {
        'all': 'var(--transition-all)',
        'colors': 'var(--transition-colors)',
        'opacity': 'var(--transition-opacity)',
        'shadow': 'var(--transition-shadow)',
        'transform': 'var(--transition-transform)',
        'smooth': 'var(--transition-smooth)',
      },
      transitionDuration: {
        '75': 'var(--duration-75)',
        '100': 'var(--duration-100)',
        '150': 'var(--duration-150)',
        '200': 'var(--duration-200)',
        '300': 'var(--duration-300)',
        '500': 'var(--duration-500)',
        '700': 'var(--duration-700)',
        '1000': 'var(--duration-1000)',
      },
      transitionTimingFunction: {
        'linear': 'var(--ease-linear)',
        'in': 'var(--ease-in)',
        'out': 'var(--ease-out)',
        'in-out': 'var(--ease-in-out)',
        'smooth': 'var(--ease-smooth)',
        'bounce': 'var(--ease-bounce)',
        'elastic': 'var(--ease-elastic)',
      },
        keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [
    // Only keep plugins that are actually used
    require("tailwindcss-animate"), // For shadcn/ui animations
    // Note: typography plugin is commented out as it's not used
    // require("@tailwindcss/typography"), // Uncomment if you need typography utilities
  ],
} satisfies Config;
