apiVersion: v1
kind: Service
metadata:
  name: mariia-app-service
  namespace: mariia-platform
  labels:
    app: mariia-hub
    component: frontend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: mariia-hub
    component: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cache-service
  namespace: mariia-platform
  labels:
    app: mariia-hub
    component: cache
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  - name: metrics
    port: 9121
    targetPort: 9121
    protocol: TCP
  selector:
    app: mariia-hub
    component: cache
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: mariia-platform
  labels:
    app: mariia-hub
    component: database
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: mariia-hub
    component: database
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-replica-service
  namespace: mariia-platform
  labels:
    app: mariia-hub
    component: database-replica
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: mariia-hub
    component: database-replica