{{- /*
Validate values before rendering the template
*/}}
{{- include "mariia-hub.validateValues" . }}

{{- /*
Deployment for Mariia Hub Application
*/}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mariia-hub.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mariia-hub.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
    app.kubernetes.io/tier: frontend
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.podAnnotations }}
  {{- toYaml .Values.podAnnotations | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  {{- if .Values.updateStrategy }}
  strategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- else }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "mariia-hub.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: app
      app.kubernetes.io/tier: frontend
  template:
    metadata:
      labels:
        {{- include "mariia-hub.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: app
        app.kubernetes.io/tier: frontend
        {{- if .Values.podLabels }}
        {{- toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- if .Values.commonAnnotations }}
        {{- toYaml .Values.commonAnnotations | nindent 8 }}
        {{- end }}
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mariia-hub.serviceAccountName" . }}
      {{- if .Values.priorityClass }}
      priorityClassName: {{ .Values.priorityClass }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      {{- if .Values.initContainers }}
      initContainers:
        {{- toYaml .Values.initContainers | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ include "mariia-hub.name" . }}
        securityContext:
          {{- toYaml .Values.containerSecurityContext | nindent 10 }}
        image: {{ include "mariia-hub.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: https
          containerPort: 8443
          protocol: TCP
        {{- if .Values.monitoring.enabled }}
        - name: metrics
          containerPort: 9090
          protocol: TCP
        {{- end }}
        env:
        - name: NODE_ENV
          value: {{ .Values.env.NODE_ENV | quote }}
        - name: APP_NAME
          value: {{ .Values.env.APP_NAME | quote }}
        - name: APP_VERSION
          value: {{ .Values.env.APP_VERSION | quote }}
        - name: APP_URL
          value: {{ .Values.env.APP_URL | quote }}
        - name: DEFAULT_CURRENCY
          value: {{ .Values.env.DEFAULT_CURRENCY | quote }}
        - name: DEFAULT_LOCALE
          value: {{ .Values.env.DEFAULT_LOCALE | quote }}
        - name: ENABLE_ANALYTICS
          value: {{ .Values.env.ENABLE_ANALYTICS | quote }}
        - name: ENABLE_PWA
          value: {{ .Values.env.ENABLE_PWA | quote }}
        - name: LOG_LEVEL
          value: {{ .Values.env.LOG_LEVEL | quote }}
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ include "mariia-hub.secretName" . }}
              key: SUPABASE_URL
        - name: SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "mariia-hub.secretName" . }}
              key: SUPABASE_ANON_KEY
        - name: STRIPE_PUBLISHABLE_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "mariia-hub.secretName" . }}
              key: STRIPE_PUBLISHABLE_KEY
        - name: GA4_MEASUREMENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "mariia-hub.secretName" . }}
              key: GA4_MEASUREMENT_ID
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: {{ include "mariia-hub.secretName" . }}
              key: SENTRY_DSN
        {{- if .Values.postgresql.enabled }}
        - name: DATABASE_URL
          value: {{ include "mariia-hub.postgresql.connectionString" . }}
        - name: POSTGRES_HOST
          value: {{ include "mariia-hub.postgresql.fullname" . }}
        - name: POSTGRES_PORT
          value: {{ .Values.postgresql.primary.service.ports.postgresql | quote }}
        - name: POSTGRES_DB
          value: {{ .Values.postgresql.auth.database | quote }}
        - name: POSTGRES_USER
          value: {{ .Values.postgresql.auth.username | quote }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "mariia-hub.postgresql.secretName" . }}
              key: {{ .Values.postgresql.auth.secretKeys.adminPasswordKey }}
        {{- end }}
        {{- if .Values.redis.enabled }}
        - name: REDIS_HOST
          value: {{ include "mariia-hub.redis.fullname" . }}
        - name: REDIS_PORT
          value: {{ .Values.redis.master.service.ports.redis | quote }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "mariia-hub.redis.secretName" . }}
              key: {{ .Values.redis.auth.existingSecretPasswordKey }}
        - name: REDIS_DB
          value: {{ .Values.redis.database | quote }}
        {{- end }}
        - name: BUILD_SHA
          value: {{ .Values.build.sha | quote }}
        - name: BUILD_DATE
          value: {{ .Values.build.date | quote }}
        - name: BUILD_TIME
          value: {{ .Values.build.time | quote }}
        {{- if .Values.extraEnv }}
        {{- toYaml .Values.extraEnv | nindent 8 }}
        {{- end }}
        {{- if .Values.extraEnvFrom }}
        envFrom:
        {{- toYaml .Values.extraEnvFrom | nindent 8 }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- if .Values.lifecycle }}
        lifecycle:
          {{- toYaml .Values.lifecycle | nindent 10 }}
        {{- end }}
        volumeMounts:
        {{- if .Values.volumes.nginxCache.enabled }}
        - name: nginx-cache
          mountPath: {{ .Values.volumes.nginxCache.mountPath }}
        {{- end }}
        {{- if .Values.volumes.appLogs.enabled }}
        - name: app-logs
          mountPath: {{ .Values.volumes.appLogs.mountPath }}
        {{- end }}
        - name: tmp
          mountPath: /tmp
        {{- if .Values.extraVolumeMounts }}
        {{- toYaml .Values.extraVolumeMounts | nindent 8 }}
        {{- end }}
        {{- if .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.startupProbe }}
        startupProbe:
          {{- toYaml .Values.startupProbe | nindent 10 }}
        {{- end }}
      {{- if .Values.sidecars }}
      {{- toYaml .Values.sidecars | nindent 6 }}
      {{- end }}
      {{- if .Values.extraContainers }}
      {{- toYaml .Values.extraContainers | nindent 6 }}
      {{- end }}
      volumes:
      {{- if .Values.volumes.nginxCache.enabled }}
      - name: nginx-cache
        persistentVolumeClaim:
          claimName: {{ include "mariia-hub.nginxCacheVolumeName" . }}
      {{- end }}
      {{- if .Values.volumes.appLogs.enabled }}
      - name: app-logs
        persistentVolumeClaim:
          claimName: {{ include "mariia-hub.appLogsVolumeName" . }}
      {{- end }}
      - name: tmp
        emptyDir: {}
      {{- if .Values.extraVolumes }}
      {{- toYaml .Values.extraVolumes | nindent 6 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.dnsConfig }}
      dnsConfig:
        {{- toYaml .Values.dnsConfig | nindent 8 }}
      {{- end }}
      {{- if .Values.hostAliases }}
      hostAliases:
        {{- toYaml .Values.hostAliases | nindent 8 }}
      {{- end }}
      {{- if .Values.podManagementPolicy }}
      podManagementPolicy: {{ .Values.podManagementPolicy }}
      {{- end }}