{{- if include "mariia-hub.ingress.enabled" . }}
{{- $ingressApiVersion := "networking.k8s.io/v1" }}
{{- if semverCompare "<1.19-0" .Capabilities.KubeVersion.GitVersion }}
{{- $ingressApiVersion = "networking.k8s.io/v1beta1" }}
{{- end }}
{{- if semverCompare "<1.14-0" .Capabilities.KubeVersion.GitVersion }}
{{- $ingressApiVersion = "extensions/v1beta1" }}
{{- end }}

apiVersion: {{ $ingressApiVersion }}
kind: Ingress
metadata:
  name: {{ include "mariia-hub.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mariia-hub.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingress
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: {{ .pathType | default "Prefix" }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "mariia-hub.serviceName" $ }}
                port:
                  name: http
              {{- else }}
              serviceName: {{ include "mariia-hub.serviceName" $ }}
              servicePort: {{ $.Values.service.ports.http }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}